baseURL = 'https://healing-honey-2026.pages.dev/'
languageCode = 'uk-UA'
title = 'Блог пасічника Сергія Поліщука:: Цілющий мед'
theme = 'pehtheme-hugo'

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Блог пасічника Сергія Поліщука про прополіс, мед, настоянки та практичний досвід бджільництва.'
	mainSections = 'posts'

[author]
	name = 'Сергій Поліщук'
	bio = 'Пасічник з власною життєвою філософією'
	avatar = '/images/PSV.jpg'
	twitter = 'https://twitter.com/insertapps'

[pagination]
	pagerSize = 6 # <- Set the desired number of posts per page 

[menu] # Menu management
	[[menu.main]]
name = 'Головна'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Про автора'
pageRef = '/about'
weight = 20

[[menu.main]]
name = 'Рецепти'
pageRef = '/tags/recepty/'
weight = 30

[[menu.main]]
name = 'Прополіс'
pageRef = '/tags/propolis/'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'
	disableKinds = ["taxonomy", "term"]